version: '3'
services:
  mysql:
    image: "mysql/mysql-server:5.7"
    volumes:
      - db_data:/var/lib/mysql
    env_file: .env-mysql
    restart: unless-stopped
    networks:
      - net
  flaskp:
    build: .
    ports:
      - "8000:5000"
    env_file: .env
    restart: unless-stopped
    depends_on:
      - mysql
    links:
      - mysql:dbserver
    networks:
      - net

volumes:
  db_data: {}

networks:
  net: